language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: X+IjwAeXfF/PmpyDNsx6R7nMNnew3loxwDFsLnxFLVmbX+2e8U+PtXz+UGwkBGCen/17m3UBpZFor9UF0an+QC0w5bYezo1SvkYvq1ZxMEcLFlLK4P+XKmwiNv9oNayyGEx78J6XpKX9o4mzjjunzspU+iVX+Yos0Jn9jW0I+N3oN0Ny7AdJkOIxlEISQMbQOqPZr4V5Jb3tfjOCuqeyo95uZmGK3EZOf2AVIP1BHXk5rU3hCSGARFr9rJ10C3wyEEKgPNj/SarM1pf3PoXnkizZlVU+k7naeUDVE7IV9AzdL+kYw3dN4TXoxfwpXR4RENCxAyOlm7UmSj7Fp2vn+QoCUIOu1G1BEEQvV2K1r4mhmJbpd40TLwZLU85/xjRxB0lsxpCyZ+tdhDDGngNuy9XqT7ZBFGufHTO6XdFeuH2zrvVPXIH7U0l3ZZ8UQwCBR6fMApgNzdDC1MTeGkopQLDaBGkUnkD7yK1USveyZEVBZWtXn8Kdej7nT8bQcNcpreZWchZ83xDa5PB00uKiM+/6Qa98Hg/8FIy6Z9y2RX5EYcd/wTJmobu+FJAgrXMbyOaalpSopKCRe0vQkLljVCNOYgm3UsJfFn05n0Ma6jksqbnz5C/0bY+1137K8y1jSjlmfuPGEsTbtkkIz5jYUp1x6UZOyQdFFP2yyothCm0=
  - secure: f1cN7jBqSOj8CiNAdU3Y9OOvaqGcsr7aWWF7mNUeROhZe41tfrmg4bVs9RAMuIpPSQW0RAcu9JxexfimUOf6UyyDrshwOezpjAeUDeXevBZHdf0qWjawP9+a+WRlW9s5UynGsNX0jncN/u7Oe0sqT/5jmNR+t5IQvNzOUK7tS4S53OVzlURVm4Euos9uwSdcIFnMonujayJM6pfBv/kPur9VB+U15/3pYe6bzuW1vHeJH1EIQlb6TwgBKjrdMfOpm/Xe+KAFiVAWP9SyP7F1QIHeKS/Vnz7KIqZ86aQg2XZXhJEp/YS+exairZF++LPKDcJ9WJ9iiqp6Fdmu2vW/4qcLKI1XA1f+IcSsoLL9IEICwU4Zg4LpfRH5xjRgSlfvIMikY8A1ggP9H1cCR7f7kUaSnYn52eA+Ae8zzaKWSYQcpah8zJcQUZJzLdgFSmMT1JA9+aNVP6m/EFoVZtacRXacDWIsWz5tLTZ59OF5sYg0p/ruoHrNM5MojTlHGBhQDiAqeIJuVuATWXUSfOfDKpn43IdAZiH5VUM+qoyc7Nx8mm7D0Pn3Aro93teW/XeaOOeOg2c6KiZdqGg5LAlSNjG/Lnq+V27URqx3HVYsbhYHm9uRJv+oEy251LY3ngrLrlTAkz8Yz1bSQFjfZEhxqcOsOPqG499mE32GBbbgS78=
