language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: VfmxkGt+aAkvaupSedlkqRv/IPnoiazg/DX6Ma2myGvRixbINRxGdyEja1p+aF4snMrbfMzhh1h5OnTcZtVCqH10hMOoRe6posRMiQ3Tt3Y1Oomumu77Z3YMy7LCjqDhUhwZcOMsobuaHq3l2KTOUxv6sMgrlukRyCQ2Qft0WiNTCe67oOT1lBEkQKAHi6fexOwAMdd2RYU6zbqJwT8Reb1WhKIMvpkxwjiVhT6eEOWT2pzXwsQFj4NqptFE7RGDc6r01/4yU9MGsYK08nmweGn6NDio3aRgBUJ18ktheKcErDJzUzW4P6G4Hehfq/f2yevsUvFT86l69RVyu5O7H9PIcxC1HlsI1wMijRWDB8tmogaYrIq1lg14HFBZ1/jCi86fTEhJ1gZSP7EVyZjER/Q2ixvMPj+FYCbqFb7d9GKvGv9MwGjz+WSmlqsy2jWeuPxJ2BBrIggiOGJ0QB2w5dnhuZLOLxQb9T0fiq08ByOdkYk94fnd8EAq7PvD6RVKaGvzYk7l5MqXXePEVueAWAwkJ+A3EZ/4ZE3LXmUE35PiuVDQx3XfDg9rHt0Ucoj7DwfOF1LgrA1p+8EhGr9DfujsCqESyE60iNyOechmy55UkS/Rk6sIrPW6OaDGoirvcpOzFkej6PHr45vS8ITPFXBNqYiI8AHHBlUWyU2bBow=
  - secure: DYNb4dF2lFv23qnHP9o5/fT74idiJLRkI37J3TC0Z4E0ECT1JStpPyks6+jC2g5y35mplwUxAEdrrIp0YNFB6vWh242YZkjyqb1jpUOVBPMXBWXZbhzMIUPesSISIMYGXNfapnTBBhDu2PticzPJPNVEPa7wLltTJZfpH8gYn9TKd+ne395huSwb2Fa312Deir1c9ZgM2Rir3CjjtawUZ9oi/Dd2RsQE8OnE84xfKwuml+dMASnUcvZIWRtTC853yGLlrGkyTv5XS9iDxj7dFKs+OLCgw1tTLns9I35qwTja7nCDIfDFFiN5/SlV3qq9UP5cfhWabq6dmjle7X8Dd6n0tXHwZ3pRIuB+XRn6lD9byV1TME1pDd7j7aAF2OaXdJOXdHsTvDYNqKnDe68ExmYgvA/aOqG+/5u+cbSxtHYgO07+krihbIRDzjn5JX4R8SeuGKZdMtoPQ0fK/UorKTVO0ihbiUuHQVcs4mmLIiykAafLspYXIZxKizdfaIM9yEHKVBFg6/WxgHdpnGed654Pca1l79F9VupmE8dSrGqPHEGIhIdmUTzE4WRA/R+OcR0UNnfW1WIY8ZlSxvs/i3kYWoWzTV6NCozoX+TVyVUkle5bX581luo1Dr0qkRFYmcSGsSF2nieXC5xtxj1pfetN8lVmGbSD7MUZgdfjKZs=
